//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS.Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public long ID { get; set; }
        public string Reason { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public string Date { get; set; }
        public string Department { get; set; }
        public string Gender { get; set; }
    }
}
