//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS.Food
{
    using System;
    using System.Collections.Generic;
    
    public partial class LunchRegister
    {
        public int ID { get; set; }
        public string Staff_name { get; set; }
        public string Staff_email { get; set; }
        public string time_booked { get; set; }
        public string Date { get; set; }
    }
}
