//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS.Customization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customization
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Website { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string TagLine { get; set; }
        public string Email { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string Location { get; set; }
    }
}
