//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAAS.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday_Management_Config
    {
        public int ID { get; set; }
        public string HolidayName { get; set; }
        public string HolidayType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
